# Generated by Django 4.2.11 on 2024-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('surName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
