# Generated by Django 4.2.11 on 2024-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_stud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='nicky',
        ),
        migrations.AddField(
            model_name='stud',
            name='nanny',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
